apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  API_VERSION: "v1.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_API_URL: "http://backend-service:8000"
